# Manipulation of Airbnb Data

# Data Inspection

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('listings.csv')

In [3]:
df.head(1)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,5396,https://www.airbnb.com/rooms/5396,20230313171257,2023-03-14,city scrape,Explore the heart of old Paris,"Cozy, well-appointed and graciously designed s...","You are within walking distance to the Louvre,...",https://a0.muscache.com/pictures/52413/f9bf76f...,7903,...,4.83,4.95,4.54,7510402838018,f,1,1,0,0,1.99

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56726 entries, 0 to 56725
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            56726 non-null  int64
 1   listing_url                                   56726 non-null  object
 2   scrape_id                                     56726 non-null  int64
 3   last_scraped                                  56726 non-null  object
 4   source                                        56726 non-null  object
 5   name                                          56689 non-null  object
 6   description                                   56161 non-null  object
 7   neighborhood_overview                         32447 non-null  object
 8   picture_url                                   56725 non-null  object
 9   host_id                                       56726 non-null  int64
 10  host_url                                      56726 non-null  object
 11  host_name                                     56708 non-null  object
 12  host_since                                    56708 non-null  object
 13  host_location                                 46634 non-null  object
 14  host_about                                    26865 non-null  object
 15  host_response_time                            31149 non-null  object
 16  host_response_rate                            31149 non-null  object
 17  host_acceptance_rate                          35410 non-null  object
 18  host_is_superhost                             56686 non-null  object
 19  host_thumbnail_url                            56708 non-null  object
 20  host_picture_url                              56708 non-null  object
 21  host_neighbourhood                            32895 non-null  object
 22  host_listings_count                           56708 non-null  float64
 23  host_total_listings_count                     56708 non-null  float64
 24  host_verifications                            56708 non-null  object
 25  host_has_profile_pic                          56708 non-null  object
 26  host_identity_verified                        56708 non-null  object
 27  neighbourhood                                 32447 non-null  object
 28  neighbourhood_cleansed                        56726 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      56726 non-null  float64
 31  longitude                                     56726 non-null  float64
 32  property_type                                 56726 non-null  object
 33  room_type                                     56726 non-null  object
 34  accommodates                                  56726 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                56611 non-null  object
 37  bedrooms                                      47631 non-null  float64
 38  beds                                          55973 non-null  float64
 39  amenities                                     56726 non-null  object
 40  price                                         56726 non-null  object
 41  minimum_nights                                56726 non-null  int64
 42  maximum_nights                                56726 non-null  int64
 43  minimum_minimum_nights                        56722 non-null  float64
 44  maximum_minimum_nights                        56722 non-null  float64
 45  minimum_maximum_nights                        56722 non-null  float64
 46  maximum_maximum_nights                        56722 non-null  float64
 47  minimum_nights_avg_ntm                        56722 non-null  float64
 48  maximum_nights_avg_ntm                        56722 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              56726 non-null  object
 51  availability_30                               56726 non-null  int64
 52  availability_60                               56726 non-null  int64
 53  availability_90                               56726 non-null  int64
 54  availability_365                              56726 non-null  int64
 55  calendar_last_scraped                         56726 non-null  object
 56  number_of_reviews                             56726 non-null  int64
 57  number_of_reviews_ltm                         56726 non-null  int64
 58  number_of_reviews_l30d                        56726 non-null  int64
 59  first_review                                  45631 non-null  object
 60  last_review                                   45631 non-null  object
 61  review_scores_rating                          45631 non-null  float64
 62  review_scores_accuracy                        45108 non-null  float64
 63  review_scores_cleanliness                     45112 non-null  float64
 64  review_scores_checkin                         45099 non-null  float64
 65  review_scores_communication                   45109 non-null  float64
 66  review_scores_location                        45097 non-null  float64
 67  review_scores_value                           45095 non-null  float64
 68  license                                       38063 non-null  object
 69  instant_bookable                              56726 non-null  object
 70  calculated_host_listings_count                56726 non-null  int64
 71  calculated_host_listings_count_entire_homes   56726 non-null  int64
 72  calculated_host_listings_count_private_rooms  56726 non-null  int64
 73  calculated_host_listings_count_shared_rooms   56726 non-null  int64
 74  reviews_per_month                             45631 non-null  float64
dtypes: float64(23), int64(17), object(35)
memory usage: 32.5+ MB

In [5]:
df.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,5.672600e+04,5.672600e+04,5.672600e+04,56708.000000,56708.000000,0.0,56726.000000,56726.000000,56726.000000,0.0,...,45112.000000,45099.000000,45109.000000,45097.000000,45095.000000,56726.000000,56726.000000,56726.000000,56726.000000,45631.000000
mean,1.973188e+17,2.023031e+13,1.295704e+08,21.893948,32.803238,NaN,48.864290,2.344470,3.048919,NaN,...,4.589212,4.786115,4.800066,4.799382,4.590021,15.104643,14.330748,0.622307,0.015742,1.009644
std,3.209526e+17,0.000000e+00,1.547738e+08,93.175233,143.030468,NaN,0.018055,0.033243,1.611676,NaN,...,0.519631,0.401047,0.396593,0.344041,0.470871,51.584652,51.453338,4.438866,0.263379,1.362947
min,5.396000e+03,2.023031e+13,2.750000e+02,1.000000,1.000000,NaN,48.816080,2.235490,0.000000,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,1.629361e+07,2.023031e+13,1.537846e+07,1.000000,1.000000,NaN,48.851310,2.323630,2.000000,NaN,...,4.440000,4.750000,4.750000,4.750000,4.470000,1.000000,1.000000,0.000000,0.000000,0.160000
50%,3.663390e+07,2.023031e+13,4.925020e+07,1.000000,2.000000,NaN,48.865590,2.347680,2.000000,NaN,...,4.740000,4.910000,4.940000,4.900000,4.700000,1.000000,1.000000,0.000000,0.000000,0.520000
75%,5.978393e+17,2.023031e+13,2.125869e+08,3.000000,4.000000,NaN,48.878690,2.368830,4.000000,NaN,...,4.950000,5.000000,5.000000,5.000000,4.880000,2.000000,1.000000,0.000000,0.000000,1.330000
max,8.463336e+17,2.023031e+13,5.049987e+08,2139.000000,3629.000000,NaN,48.901670,2.467120,16.000000,NaN,...,5.000000,5.000000,5.000000,5.000000,5.000000,447.000000,447.000000,91.000000,10.000000,49.550000

In [6]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [7]:
df.shape

(56726, 75)

# Cleaning Data

### Select column to exploit

In [8]:
df1 = df[['id','listing_url','name','description','neighborhood_overview','host_id','host_url','host_name','neighbourhood_cleansed','latitude','longitude','room_type','price','minimum_nights','minimum_nights','availability_365','number_of_reviews','last_review','calculated_host_listings_count','reviews_per_month']].copy()
df1.head(1)

,id,listing_url,name,description,neighborhood_overview,host_id,host_url,host_name,neighbourhood_cleansed,latitude,longitude,room_type,price,minimum_nights,minimum_nights,availability_365,number_of_reviews,last_review,calculated_host_listings_count,reviews_per_month
0,5396,https://www.airbnb.com/rooms/5396,Explore the heart of old Paris,"Cozy, well-appointed and graciously designed s...","You are within walking distance to the Louvre,...",7903,https://www.airbnb.com/users/show/7903,Borzou,Hôtel-de-Ville,48.85247,2.35835,Entire home/apt,$124.00,15,15,184,332,2023-02-18,1,1.99

### show how many NaN values

In [9]:
df1.isna().sum()

id                                    0
listing_url                           0
name                                 37
description                         565
neighborhood_overview             24279
host_id                               0
host_url                              0
host_name                            18
neighbourhood_cleansed                0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
minimum_nights                        0
availability_365                      0
number_of_reviews                     0
last_review                       11095
calculated_host_listings_count        0
reviews_per_month                 11095
dtype: int64

### last_review Data transformation into datetime

In [10]:
df1['last_review']

0        2023-02-18
1        2023-03-15
2        2015-09-14
3               NaN
4        2022-10-21
            ...
56721           NaN
56722           NaN
56723           NaN
56724           NaN
56725           NaN
Name: last_review, Length: 56726, dtype: object

In [11]:
df1['last_review'] = pd.to_datetime(df1['last_review'])
df1['last_review']

0       2023-02-18
1       2023-03-15
2       2015-09-14
3              NaT
4       2022-10-21
           ...
56721          NaT
56722          NaT
56723          NaT
56724          NaT
56725          NaT
Name: last_review, Length: 56726, dtype: datetime64[ns]

### replace NaN value by max value in last_review

In [12]:
df1['last_review'] = df1['last_review'].fillna(df1['last_review'].max())
df1['last_review']

0       2023-02-18
1       2023-03-15
2       2015-09-14
3       2023-03-26
4       2022-10-21
           ...
56721   2023-03-26
56722   2023-03-26
56723   2023-03-26
56724   2023-03-26
56725   2023-03-26
Name: last_review, Length: 56726, dtype: datetime64[ns]

### Replace NaN in reviews_per_month by 0

In [13]:
df1['reviews_per_month'] = df1['reviews_per_month'].fillna(0)
df1['reviews_per_month']

0        1.99
1        2.26
2        0.04
3        0.00
4        0.35
         ...
56721    0.00
56722    0.00
56723    0.00
56724    0.00
56725    0.00
Name: reviews_per_month, Length: 56726, dtype: float64

### replace NaN value in name, host_name, description, neighbourhood_overview and neighbourhood with ""

In [14]:
arraytofil = ['name', 'host_name', 'description', 'neighborhood_overview', 'neighbourhood_cleansed']
df1[arraytofil] = df1[arraytofil].fillna("")

 ### Check if all NaN as been replaced

In [15]:
df1.isna().sum()

id                                0
listing_url                       0
name                              0
description                       0
neighborhood_overview             0
host_id                           0
host_url                          0
host_name                         0
neighbourhood_cleansed            0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
minimum_nights                    0
availability_365                  0
number_of_reviews                 0
last_review                       0
calculated_host_listings_count    0
reviews_per_month                 0
dtype: int64

### Cleaning col Price for remove '$'

In [16]:
df1['price'] = df1['price'].str.replace('$', "")
df1['price']

0        124.00
1        130.00
2        140.00
3         75.00
4        160.00
          ...
56721    640.00
56722    538.00
56723    600.00
56724    181.00
56725    300.00
Name: price, Length: 56726, dtype: object

### Add new col for getting night reserved on year in reserved_365

In [17]:
df1['reserved_365'] = (365 - df1['availability_365'])
df1.head(1)

,id,listing_url,name,description,neighborhood_overview,host_id,host_url,host_name,neighbourhood_cleansed,latitude,...,room_type,price,minimum_nights,minimum_nights,availability_365,number_of_reviews,last_review,calculated_host_listings_count,reviews_per_month,reserved_365
0,5396,https://www.airbnb.com/rooms/5396,Explore the heart of old Paris,"Cozy, well-appointed and graciously designed s...","You are within walking distance to the Louvre,...",7903,https://www.airbnb.com/users/show/7903,Borzou,Hôtel-de-Ville,48.85247,...,Entire home/apt,124.00,15,15,184,332,2023-02-18,1,1.99,181


# Analyze Data

### How many host does we have ?

In [18]:
df1['host_id'].nunique()

42490

### Show the top 10 host with the most of listing by ID

In [19]:
top_hosts = df1['host_id'].value_counts().nlargest(10)
top_hosts

host_id
314994947    447
50978178     230
50502817     214
7642792      196
440295601    195
33889201     182
458533553    165
26981054     156
402191311    141
6053288      131
Name: count, dtype: int64

### Show the top 10 host with the most of listing by ID name

In [20]:
top_host = df1.groupby(['host_id','host_name'])['host_id'].value_counts().nlargest(10)
top_host

host_id    host_name
314994947  Blueground          447
50978178   Sebastien           230
50502817   Pierre De WeHost    214
7642792    Ludovic             196
440295601  Gaelle              195
33889201   Veeve               182
458533553  Joffrey             165
26981054   Cédric              156
402191311  GuestReady          141
6053288    Anna                131
Name: count, dtype: int64

### Show all listing of the top 10

In [21]:
top_hosts_df = df1[df1['host_id'].isin(top_hosts.index)]

In [22]:
top_hosts_df

,id,listing_url,name,description,neighborhood_overview,host_id,host_url,host_name,neighbourhood_cleansed,latitude,...,room_type,price,minimum_nights,minimum_nights,availability_365,number_of_reviews,last_review,calculated_host_listings_count,reviews_per_month,reserved_365
190,52931,https://www.airbnb.com/rooms/52931,Charming apt in the 17th of Paris - Terrace 25m2,I will be delighted to welcome you to my charm...,"In some streets, Les Épinettes has also become...",50502817,https://www.airbnb.com/users/show/50502817,Pierre De WeHost,Batignolles-Monceau,48.896130,...,Entire home/apt,141.00,3,3,78,8,2023-02-24,214,1.79,287
662,810543,https://www.airbnb.com/rooms/810543,GuestReady - Spacious Bright flat near Louvre,This chic 1 bedroom apartment in the trendy 1s...,The apartment is perfectly located in the hear...,402191311,https://www.airbnb.com/users/show/402191311,GuestReady,Louvre,48.866310,...,Entire home/apt,125.00,1,1,2,76,2023-01-07,141,0.64,363
966,1022819,https://www.airbnb.com/rooms/1022819,✹Cocoon in the center of Montmartere✹,The accommodation can accommodate two people w...,A very quiet place in the heart of a very busy...,50502817,https://www.airbnb.com/users/show/50502817,Pierre De WeHost,Buttes-Montmartre,48.887900,...,Entire home/apt,80.00,3,3,162,120,2022-06-01,214,1.01,203
1323,1430881,https://www.airbnb.com/rooms/1430881,"Fleur de Rosiers, 1BR/1BA, 3 people",28 square meters apartment on the third floor ...,"Le Marais, it's the festive, fashion, artistic...",7642792,https://www.airbnb.com/users/show/7642792,Ludovic,Hôtel-de-Ville,48.856230,...,Entire home/apt,133.00,91,91,0,9,2017-10-17,196,0.08,365
1366,1452226,https://www.airbnb.com/rooms/1452226,"Parfum d'Histoire, 3BR/1BA 6 people","Beautiful apartment of 62 m2 floor, with two b...","Le Marais, it's the festive, fashion, artistic...",7642792,https://www.airbnb.com/users/show/7642792,Ludovic,Temple,48.861000,...,Entire home/apt,249.00,91,91,68,30,2017-05-01,196,0.27,297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56661,846322669044068092,https://www.airbnb.com/rooms/846322669044068092,"Ternes 1br w/ elevator, nr Arc de Triomphe",Show up and start living from day one in Paris...,This neighborhood takes its name from the Plac...,314994947,https://www.airbnb.com/users/show/314994947,Blueground,Batignolles-Monceau,48.879684,...,Entire home/apt,132.00,31,31,365,0,2023-03-26,447,0.00,0
56672,846329760591558172,https://www.airbnb.com/rooms/846329760591558172,"Trocadero 3br w/ balcony, nr Place du Trocadéro",Show up and start living from day one in Paris...,"Within the borders of the 16th, Trocadéro host...",314994947,https://www.airbnb.com/users/show/314994947,Blueground,Passy,48.869268,...,Entire home/apt,312.00,31,31,337,0,2023-03-26,447,0.00,28
56673,846332777690107540,https://www.airbnb.com/rooms/846332777690107540,"Trocadéro 2br w/ elevator, nr Eiffel Tower",Show up and start living from day one in Paris...,"Within the borders of the 16th, Trocadéro host...",314994947,https://www.airbnb.com/users/show/314994947,Blueground,Passy,48.866772,...,Entire home/apt,253.00,31,31,0,0,2023-03-26,447,0.00,365
56676,846333585388413037,https://www.airbnb.com/rooms/846333585388413037,"Champs Elysées 2br w/ balcony, nr Montaigne St","Discover the best of Paris, with this two-bedr...","One of Paris’s best-loved monuments, the histo...",314994947,https://www.airbnb.com/users/show/314994947,Blueground,Élysée,48.873735,...,Entire home/apt,350.00,31,31,0,0,2023-03-26,447,0.00,365
56712,844680838536598952,https://www.airbnb.com/rooms/844680838536598952,Old apartment for 4 - Paris 20 E,Travelers particularly appreciated this accomm...,The Père-Lachaise Saint Frageau district is a ...,6053288,https://www.airbnb.com/users/show/6053288,Anna,Ménilmontant,48.865593,...,Entire home/apt,112.00,3,3,19,0,2023-03-26,131,0.00,346

### Getting ID of top 1 who's having most listing

In [26]:
highestListing = df1['host_id'].value_counts().idxmax()
highestListing

314994947

### Getting neighborhood in Paris

In [27]:
df1['neighbourhood_cleansed'].unique()

array(['Hôtel-de-Ville', 'Opéra', 'Louvre', 'Popincourt',
       'Buttes-Montmartre', 'Luxembourg', 'Gobelins', 'Entrepôt',
       'Batignolles-Monceau', 'Temple', 'Buttes-Chaumont', 'Bourse',
       'Ménilmontant', 'Observatoire', 'Panthéon', 'Vaugirard', 'Élysée',
       'Reuilly', 'Passy', 'Palais-Bourbon'], dtype=object)

### Getting listing types

In [28]:
df1['room_type'].unique()

array(['Entire home/apt', 'Private room', 'Shared room', 'Hotel room'],
      dtype=object)

### Show the top 10 listing with the most of reviews

In [33]:
largestReview = df1.nlargest(10, 'number_of_reviews' )

In [34]:
largestReview

,id,listing_url,name,description,neighborhood_overview,host_id,host_url,host_name,neighbourhood_cleansed,latitude,...,room_type,price,minimum_nights,minimum_nights,availability_365,number_of_reviews,last_review,calculated_host_listings_count,reviews_per_month,reserved_365
21647,26244787,https://www.airbnb.com/rooms/26244787,"Double/Twin Room, close to Opera and the Louvr...",<b>The space</b><br />The Daunou Opera enjoys ...,,98020850,https://www.airbnb.com/users/show/98020850,Lionel,Bourse,48.86958,...,Hotel room,364.00,1,1,337,2524,2023-03-12,8,49.55,28
14749,17222007,https://www.airbnb.com/rooms/17222007,Sweet & cosy room next to Canal Saint Martin ❤️,The room is located right in the heart of la R...,The room I offer is right in the middle of a v...,84901734,https://www.airbnb.com/users/show/84901734,Alexandra,Entrepôt,48.86989,...,Private room,147.00,1,1,99,2052,2023-02-27,5,28.79,266
31468,41020735,https://www.airbnb.com/rooms/41020735,"Bed in Dorm of 8 Beds ""The Big One"" in Paris","Welcome to Les Piaules, our hostel & bar in do...",Les Piaules hostel is located in Paris arty & ...,315206797,https://www.airbnb.com/users/show/315206797,Les Piaules,Popincourt,48.86998,...,Shared room,41.00,1,1,364,1647,2023-02-27,11,44.19,1
26941,35145338,https://www.airbnb.com/rooms/35145338,Nice Room for 2 people,Hotel de l'Aqueduc is located near the center ...,,264483496,https://www.airbnb.com/users/show/264483496,Hotel De L’Aqueduc,Entrepôt,48.88137,...,Hotel room,124.00,1,1,227,1433,2023-03-10,4,35.83,138
30717,40194697,https://www.airbnb.com/rooms/40194697,Comfortable bed in shared rooms of 8 in Paris 12e,Kick your journey off with a coffee on the 8th...,"Make your stay a magic, cocooning and romantic...",309707704,https://www.airbnb.com/users/show/309707704,The People Paris Bercy,Reuilly,48.83903,...,Shared room,42.00,1,1,106,1420,2023-02-27,10,35.41,259
25092,32518543,https://www.airbnb.com/rooms/32518543,Hotel Boronali *** - Double room in Montmartre,"Book this room, and discover the historical Pa...","Occupied since Gallo-Roman times, Montmartre h...",98087989,https://www.airbnb.com/users/show/98087989,Arthur,Buttes-Montmartre,48.88869,...,Hotel room,174.00,1,1,326,1352,2023-03-13,4,27.54,39
768,846954,https://www.airbnb.com/rooms/846954,Gde chambre ds grand appart. Salle de bain privée,Chambre 20 m2 dans appartement spacieux (120 m...,"Il est animé, ""parisien"", près du centre, très...",3125405,https://www.airbnb.com/users/show/3125405,Maguy,Popincourt,48.85416,...,Private room,58.00,1,1,4,1004,2023-03-10,1,8.08,361
24946,32057469,https://www.airbnb.com/rooms/32057469,Sweet Little Room near St Martin Canal,Welcome to Hotel Tilde!<br />Prepared for you!...,"In the 19th arrondissement of Paris, the hotel...",183489963,https://www.airbnb.com/users/show/183489963,Naïm,Buttes-Chaumont,48.88720,...,Private room,120.00,1,1,324,986,2022-07-31,9,19.80,41
1272,1249964,https://www.airbnb.com/rooms/1249964,A Journey Into The Heart Of Paris,You are looking for a private and whole apartm...,The 1st district in which abounds most monumen...,6811343,https://www.airbnb.com/users/show/6811343,Mike,Louvre,48.86486,...,Private room,149.00,1,1,146,947,2023-03-10,1,8.01,219
27199,35242476,https://www.airbnb.com/rooms/35242476,Superb room for two,"In order to guarantee the room, a pre-authoriz...",The Europe Saint-Séverin Paris Notre-Dame hote...,264941340,https://www.airbnb.com/users/show/264941340,Marine,Panthéon,48.85275,...,Hotel room,210.00,1,1,285,835,2023-02-24,10,18.24,80

### Create new col annual_Income

In [36]:
df1['price'] = df1['price'].str.replace(',', '')
df1['price'] = pd.to_numeric(df1['price'])
df1['annual_income'] = df1['price'] * df1['reserved_365']
df1.head(1)

,id,listing_url,name,description,neighborhood_overview,host_id,host_url,host_name,neighbourhood_cleansed,latitude,...,price,minimum_nights,minimum_nights,availability_365,number_of_reviews,last_review,calculated_host_listings_count,reviews_per_month,reserved_365,annual_income
0,5396,https://www.airbnb.com/rooms/5396,Explore the heart of old Paris,"Cozy, well-appointed and graciously designed s...","You are within walking distance to the Louvre,...",7903,https://www.airbnb.com/users/show/7903,Borzou,Hôtel-de-Ville,48.85247,...,124.0,15,15,184,332,2023-02-18,1,1.99,181,22444.0